# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSAFNetWorking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSAFNetWorking

  target 'iOSAFNetWorkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSAFNetWorkingUITests' do
    # Pods for testing
  end
pod 'AFNetworking'

end
